name: recycle-bin

services:
  inference-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inference-server
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
      - ./conf/config.toml:/app/conf/config.toml
      # Windows 11
      - /usr/lib/wsl:/usr/lib/wsl
    restart: unless-stopped
    devices:
      # Linux
#      - /dev/dri:/dev/dri
      # Windows 11
      - /dev/dxg
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s