name: recycle-bin

services:
  inference-server:
    image: recycle-bin-inference-server:latest
    container_name: inference-server
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
      - ./conf/config.toml:/app/conf/config.toml
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s