[stream]

[stream.1]
url = "rtsp://admin:@192.168.0.10:554"
roi_x = 482
roi_y = 18
roi_width = 955
roi_height = 940

[stream.2]
url = "rtsp://admin:@192.168.0.11:554"
roi_x = 526
roi_y = 72
roi_width = 963
roi_height = 937

[infer]
confidence_threshold = 0.5
nms_threshold = 0.4
class_names = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7"
]